on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Rust environment
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install dioxus
        run: |
          cargo install cargo-binstall
          cargo binstall -y dioxus-cli@0.7.0-alpha.3
      - name: Bundle for web
        run: dx bundle --platform web --release
      - name: Add CNAME
        run: |
          echo "token.hpkns.uk" > ./target/dx/oauth-token-generator/release/web/public/CNAME
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/dx/oauth-token-generator/release/web/public
